name: Zen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  Zen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      
      - name: Build the project
        run: dotnet build .
      
      - name: Add Msbuild package
        run: |-
          cd VerifierTest
          dotnet add package coverlet.msbuild
        
      - name: Run tests
        run: dotnet test . /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV }}
          file: VerifierTest/coverage.opencover.xml
          fail_ci_if_error: true
